// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific
// target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.OptionalMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.VerboseParser.MaxLengthNegateds" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0120:Your Switch maybe include default clause", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.CLI.CLIStepRenderer.RenderStatus(GParse.Verbose.Visitors.StepByStep.Step)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0068:Unused Method", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Optimization.MatchTreeOptimizer.MultiplyValuesClamped(System.UInt32,System.UInt32)~System.UInt32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.ExpressionParser.ParseCharacterClass~GParse.Verbose.Matchers.BaseMatcher[]" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.ExpressionParser.ParsePrefixedExpression~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.ExpressionParser.ParseSuffixedExpression(GParse.Verbose.Matchers.BaseMatcher)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.VerboseParser.InfixOperator(System.String,GParse.Verbose.OperatorAssociativity,System.String,GParse.Verbose.Matchers.BaseMatcher,GParse.Verbose.Matchers.BaseMatcher,System.Boolean)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.VerboseParser.ParseMatcher(System.Func{System.Char,System.Boolean})~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.ExpressionReconstructor.Visit(GParse.Verbose.Matchers.RepeatedMatcher)~System.String" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0037:Remove commented code.", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.MaximumMatchLengthCalculator.Visit(GParse.Verbose.Matchers.RepeatedMatcher)~System.Int32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.StepByStep.StepByStepRecorder.Execute(System.String)~GParse.Verbose.Visitors.StepByStep.Step[]" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Lexing.LexTreeCompiler.Fail(System.String,System.Boolean)~System.Linq.Expressions.Expression" )]

