[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.AllMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.AnyMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.IgnoreMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.JoinMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.NegatedMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Verbose.Optimization.TreeOptimizerOptions.OptionalMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0120:Your Switch maybe include default clause", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.CLI.CLIStepRenderer.RenderStatus(GParse.Verbose.Visitors.StepByStep.Step)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Optimization.MatchTreeOptimizer.Visit(GParse.Verbose.Matchers.RepeatedMatcher)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.MatchExpressionParser.ParseAtomic(System.Boolean)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.MatchExpressionParser.ParseCharacterClass~GParse.Verbose.Matchers.BaseMatcher[]" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.MatchExpressionParser.ParsePrefixedExpression(System.Boolean)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.MatchExpressionParser.ParseSuffixedExpression(GParse.Verbose.Matchers.BaseMatcher)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.VerboseParser.ParseMatcher(System.Func{System.Char,System.Boolean})~GParse.Verbose.Matchers.BaseMatcher" )]// This file is used by Code Analysis to maintain SuppressMessage
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.VerboseParser.InfixOperator(System.String,GParse.Verbose.OperatorAssociativity,System.String,GParse.Verbose.Matchers.BaseMatcher,GParse.Verbose.Matchers.BaseMatcher,System.Boolean)~GParse.Verbose.Matchers.BaseMatcher" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.ExpressionReconstructor.Visit(GParse.Verbose.Matchers.RepeatedMatcher)~System.String" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.StepByStep.StepByStepRecorder.Execute(System.String)~GParse.Verbose.Visitors.StepByStep.Step[]" )]// attributes that are applied to this project. Project-level
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.CompiledBaseVisitor`2.Visit(`0)~`1" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Visitors.CompiledBaseVisitor`2.Visit(`0)~`1" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Verbose.Parsing.MatchExpressionParser.ParsePrefixedExpression~GParse.Verbose.Matchers.BaseMatcher" )]
// suppressions either have no target or are given a specific
// target and scoped to a namespace, type, member, etc.
