// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific
// target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.Errors.LexError.Location" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.Errors.LexError.Message" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.IO.SourceCodeReader.SavePoint.Line" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.SourceLocation.Column" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.SourceLocation.Line" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.SourceLocation.Byte" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.SourceRange.End" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Usage", "CC0074:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:GParse.Common.SourceRange.Start" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.IO.SourceCodeReader.Rewind(GParse.Common.SourceLocation)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.IO.SourceCodeReader.Load" )]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Add(System.Int32@,System.Int32@,System.Int32@,System.Int32@)~System.Int32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Add(System.Int64@,System.Int64@,System.Int64@,System.Int64@)~System.Int64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Add(System.UInt32@,System.UInt32@,System.UInt32@,System.UInt32@)~System.UInt32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Add(System.UInt64@,System.UInt64@,System.UInt64@,System.UInt64@)~System.UInt64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Divide(System.Int32@,System.Int32@,System.Int32@,System.Int32@)~System.Int32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Divide(System.Int64@,System.Int64@,System.Int64@,System.Int64@)~System.Int64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Divide(System.UInt32@,System.UInt32@,System.UInt32@,System.UInt32@)~System.UInt32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Divide(System.UInt64@,System.UInt64@,System.UInt64@,System.UInt64@)~System.UInt64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Multiply(System.Int32@,System.Int32@,System.Int32@,System.Int32@)~System.Int32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Multiply(System.Int64@,System.Int64@,System.Int64@,System.Int64@)~System.Int64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Multiply(System.UInt32@,System.UInt32@,System.UInt32@,System.UInt32@)~System.UInt32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Multiply(System.UInt64@,System.UInt64@,System.UInt64@,System.UInt64@)~System.UInt64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Subtract(System.Int32@,System.Int32@,System.Int32@,System.Int32@)~System.Int32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Subtract(System.Int64@,System.Int64@,System.Int64@,System.Int64@)~System.Int64" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Subtract(System.UInt32@,System.UInt32@,System.UInt32@,System.UInt32@)~System.UInt32" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "<Pending>", Scope = "member", Target = "~M:GParse.Common.Math.SaturatingMath.Subtract(System.UInt64@,System.UInt64@,System.UInt64@,System.UInt64@)~System.UInt64" )]
